name: Foundation CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: 'https://npm.pkg.github.com'
      - run: sudo apt-get install build-essential libsodium-dev libboost-system-dev
      - run: npm install -g mocha
      - run: npm install
      - run: npm test
